%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-lvr2
Version:        20.11.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS lvr2 package

License:        BSD-3-Clause
URL:            https://www.las-vegas.uni-osnabrueck.de/
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python3-devel
Requires:       eigen3-devel
Requires:       flann-devel
Requires:       freeglut-devel
Requires:       gsl-devel
Requires:       hdf5-devel
Requires:       libXi-devel
Requires:       libXmu-devel
Requires:       lz4-devel
Requires:       ocl-icd-devel
Requires:       opencv-devel
Requires:       qt5-qtbase-devel
Requires:       vtk-devel
Requires:       vtk-qt
Requires:       yaml-cpp-devel
BuildRequires:  boost-devel
BuildRequires:  boost-python3-devel
BuildRequires:  cmake
BuildRequires:  eigen3-devel
BuildRequires:  flann-devel
BuildRequires:  freeglut-devel
BuildRequires:  gsl-devel
BuildRequires:  hdf5-devel
BuildRequires:  libXi-devel
BuildRequires:  libXmu-devel
BuildRequires:  lz4-devel
BuildRequires:  ocl-icd-devel
BuildRequires:  opencv-devel
BuildRequires:  qt5-qtbase-devel
BuildRequires:  vtk-devel
BuildRequires:  vtk-qt
BuildRequires:  yaml-cpp-devel
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The Las Vegas Surface Reconstruction Toolkit is an Open Source toolkit to
reconstruct triangle meshes from unordered point clouds. It supports the
generation of textured models either using colored point clouds or point clouds
plus images and according calibration matrices. The LVR toolkit provides an Open
Source C++ API for meshing and texture generation as well as an I/O interface to
store the generated meshes in different exchange formats including Stanford PLY,
Wavefront OBJ and Collada. In contrast to other meshing software, it focuses on
reconstruction of large scale environments on city scale from high resolution
point clouds.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_build -C obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/noetic

%changelog
* Thu Dec 03 2020 Sebastian Pütz <spuetz@uos.de> - 20.11.2-1
- Autogenerated by Bloom

* Sun Nov 15 2020 Sebastian Pütz <spuetz@uos.de> - 20.11.1-1
- Autogenerated by Bloom

